
name: 'Github Repository Mirror'

description: 'Action for mirror a repository to another location(default Gitee) using SSH.'

branding:
  icon: 'copy'
  color: 'orange'

runs:
  using: "composite"
  steps:
    - id: git-mirror
      run: curl -sL https://github.com/cc332030/git/raw/master/script/mirror/linux/mirror-github.sh | sh
      shell: bash
