
name: 'Github Repository Mirror'

description: 'Action for mirror a repository to another location(default Gitee) using SSH.'

branding:
  icon: 'copy'
  color: 'orange'

inputs:
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: false

runs:
  using: "composite"
  steps:
    - id: git-mirror
      run: curl -s https://raw.githubusercontent.com/cc332030/git/master/script/mirror/linux/mirror-github.sh | sh -s $*
      shell: bash
