
name: 'git mirror'

description: 'Action for mirroring a repository in another location (Bitbucket, GitHub, GitLab,…) using SSH.'

branding:
  icon: 'copy'
  color: 'orange'

inputs:
  source-repo:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''

runs:
  using: 'docker'
  image: docker://c332030/alpine-git-mirror
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.destination-repo }}
