
name: 'Github Repository Mirror'

description: 'Action for mirror a repository to another location(default Gitee) using SSH.'

branding:
  icon: 'copy'
  color: 'orange'

runs:
  using: 'docker'
  image: 'Dockerfile'
